name: dsvm_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flash: ^2.0.3+2
  flutter_bloc: ^7.3.0 # state management
  animated_splash_screen: ^1.2.0  # splash screen
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0
  bottom_bar: ^1.3.0+1
  curved_navigation_bar: ^1.0.3
  flutter_screenutil: ^5.5.2 #
  carousel_slider: ^4.1.1 # slider
  shimmer: ^2.0.0 #item loading
  flutter_svg: ^1.0.3 # svg render
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  http: ^0.13.4
  webview_flutter: ^2.1.2 # load url in app
  path_provider: ^2.0.11
  url_launcher: ^6.1.3
  cached_network_image: ^3.1.0+1
  hive: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
flutter_app_name:
  name: "Đặc Sản Vùng Miền - HHT"
flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito-Black.ttf
        weight: 900
      - asset: assets/fonts/Nunito-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/Nunito-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 700
      - asset: assets/fonts/Nunito-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Nunito-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        weight: 200
        style: italic
